### ISSUE TITLE
Running `gh` throws TypeError

### ISSUE THREAD

**Issue by weakish** [node-gh/gh#322]
```sh
; gh help

path.js:313
        throw new TypeError('Arguments to path.resolve must be strings');
              ^
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /usr/lib/node_modules/gh/lib/cmds/help.js:73:32
    at Array.forEach (native)
    at Help.run (/usr/lib/node_modules/gh/lib/cmds/help.js:72:11)
    at /usr/lib/node_modules/gh/bin/gh.js:183:34
    at Array.forEach (native)
    at /usr/lib/node_modules/gh/bin/gh.js:174:25
    at /usr/lib/node_modules/gh/node_modules/async/lib/async.js:254:17
    at /usr/lib/node_modules/gh/node_modules/async/lib/async.js:151:21
    at /usr/lib/node_modules/gh/node_modules/async/lib/async.js:251:21
```

gh 1.9.3 on node v0.10.32 under Debian sid i386

**Comment by henvic** [comment]
Should be running fine now. Expect it required node v0.12 from now on.
