### ISSUE TITLE
Error: ENOENT, no such file or directory '/usr/lib/node_modules'

### ISSUE THREAD

**Issue by MohamedBassem** [node-gh/gh#334]
After installing `gh` using `sudo npm install -g gh` and trying to run `gh` I'm getting 
```
Error: ENOENT, no such file or directory '/usr/lib/node_modules'
    at Object.fs.readdirSync (fs.js:659:18)
    at Object.exports.getPlugins (/usr/local/lib/node_modules/gh/lib/base.js:250:18)
    at Help.run (/usr/local/lib/node_modules/gh/lib/cmds/help.js:57:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/gh/lib/cmd.js:51:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```
This error looks simillar to #293 but Installing the latest version `1.9.4` didn't solve the problem.
```
$ npm -v
1.4.21
$ node -v
v0.10.25
```
I'm on Ubuntu 14.10

**Comment by randsonjs** [comment]
I get the same error on my update. But works normally here now!

After this works normally? Or not?

**Comment by MohamedBassem** [comment]
which update do you mean? I do have the latest version `1.9.4` but still getting this error.

**Comment by samanzanedo** [comment]
Try to make a synlink like:

sudo ln -s /usr/lib/nodejs/ /usr/lib/node_modules

**Comment by MohamedBassem** [comment]
@samanzanedo, your solution worked. Thank you.

**Comment by zenorocha** [comment]
What OS are you using @samanzanedo?

**Comment by samanzanedo** [comment]
Linux 3.16.0-29-generic #39-Ubuntu SMP Mon Dec 15 22:27:29 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by henvic** [comment]
Please, see https://github.com/node-gh/gh/issues/349#issuecomment-74556530.
