### ISSUE TITLE
Authentication  error?

### ISSUE THREAD

**Issue by zbeekman** [node-gh/gh#347]
I’m not sure why this is happening… maybe due to two factor authentication? Something else?
```
$ gh is -l
gh First we need authorization to use GitHub's API. Login with your GitHub account.
? Enter your GitHub user: zbeekman
? Enter your GitHub password: ********
? Enter your two-factor code: 783373

/usr/local/lib/node_modules/gh/node_modules/inquirer/node_modules/rx/dist/rx.js:4586
        throw e;
              ^
TypeError: Cannot set property 'X-GitHub-OTP' of undefined
    at PromptUI.completed (/usr/local/lib/node_modules/gh/lib/cmds/user.js:179:45)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/gh/node_modules/inquirer/lib/ui/prompt.js:68:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/gh/node_modules/inquirer/node_modules/rx/dist/rx.js:1929:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/gh/node_modules/inquirer/node_modules/rx/dist/rx.js:1866:14)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/gh/node_modules/inquirer/node_modules/rx/dist/rx.js:4604:23)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/gh/node_modules/inquirer/node_modules/rx/dist/rx.js:1866:14)
    at AnonymousObserver._onCompleted (/usr/local/lib/node_modules/gh/node_modules/inquirer/node_modules/rx/dist/rx.js:
```

Here is the install output:
```
$ sudo npm install -g gh

> execSync@1.0.2 install /usr/local/lib/node_modules/gh/node_modules/copy-paste/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2] Native extension compilation successful!
/usr/local/bin/gh -> /usr/local/lib/node_modules/gh/bin/gh.js
gh@1.9.4 /usr/local/lib/node_modules/gh
├── cli-log@0.0.8
├── userhome@0.1.0
├── truncate@1.0.4
├── which@1.0.8
├── open@0.0.5
├── wordwrap@0.0.2
├── async@0.9.0
├── nopt@3.0.1 (abbrev@1.0.5)
├── github@0.2.3
├── update-notifier@0.2.2 (is-npm@1.0.0, string-length@1.0.0, chalk@0.5.1, semver-diff@2.0.0, latest-version@1.0.0, configstore@0.3.2)
├── moment@2.9.0
├── cli-color@0.3.2 (d@0.1.1, timers-ext@0.1.0, memoizee@0.3.8, es5-ext@0.10.6)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
├── inquirer@0.7.3 (ansi-regex@1.1.0, figures@1.3.5, mute-stream@0.0.4, through@2.3.6, readline2@0.1.1, chalk@0.5.1, lodash@2.4.1, rx@2.3.25)
├── npm@2.1.18
└── copy-paste@0.3.0 (execSync@1.0.2)
```

**Comment by zenorocha** [comment]
We just made a release solving several problems, including this one you just mentioned.

https://github.com/node-gh/gh/releases/tag/v0.10.0

Please grab the latest version from npm by running: `npm -g gh`
