### ISSUE TITLE
gh is throwing an error when trying to delete a branch on git merge

### ISSUE THREAD

**Issue by henvic** [node-gh/gh#374]
```
TypeError: undefined is not a function
    at operations (/usr/local/lib/node_modules/gh/lib/cmds/pull-request.js:735:17)
    at /usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:610:21
    at /usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:249:17
    at iterate (/usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:149:13)
    at async.eachSeries (/usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:165:9)
    at _asyncMap (/usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:248:13)
    at Object.mapSeries (/usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:231:23)
    at Object.async.series (/usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:608:19)
    at PullRequest.merge (/usr/local/lib/node_modules/gh/lib/cmds/pull-request.js:740:11)
    at /usr/local/lib/node_modules/gh/lib/cmds/pull-request.js:218:22
```

**Comment by zenorocha** [comment]
+1, I got the same error yesterday

**Comment by zenorocha** [comment]
:top:
