### ISSUE TITLE
Forwarding request throws exception

### ISSUE THREAD

**Issue by ipeychev** [node-gh/gh#380]
➜  portal (master) ✔ gh pr 570 -fwd natecavanaugh
Forwarding pull request #570 to @natecavanaugh
/usr/local/lib/node_modules/gh/lib/cmds/pull-request.js:333
        git[opt_type](options.pullBranch);
                     ^
TypeError: undefined is not a function
    at /usr/local/lib/node_modules/gh/lib/cmds/pull-request.js:333:22
    at /usr/local/lib/node_modules/gh/node_modules/github/api/v3.0.0/pullRequests.js:118:17
    at callCallback (/usr/local/lib/node_modules/gh/node_modules/github/index.js:743:17)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/gh/node_modules/github/index.js:796:25)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by henvic** [comment]
Fixed with cc4c5e2758ebe58d43157de2e9b1aca35f825d35.
