### ISSUE TITLE
Fails on node v0.10.x

### ISSUE THREAD

**Issue by jwalton** [node-gh/gh#384]
```
> 16:19:42 [jwalton@nimue ~/myProject] $ node -v
v0.10.31

16:18:41 [jwalton@nimue ~/myProject] $ ./node_modules/.bin/gh help

/Users/jwalton/myProject/node_modules/gh/lib/configs.js:159
        mode: Number.parseInt('0600', 8)
                     ^
TypeError: Object function Number() { [native code] } has no method 'parseInt'
    at Object.exports.saveJsonConfig (/Users/jwalton/myProject/node_modules/gh/lib/configs.js:159:22)
    at Object.exports.createGlobalConfig (/Users/jwalton/myProject/node_modules/gh/lib/configs.js:132:10)
    at Object.exports.getGlobalConfig (/Users/jwalton/myProject/node_modules/gh/lib/configs.js:95:17)
    at getConfig (/Users/jwalton/myProject/node_modules/gh/lib/configs.js:48:32)
    at Object.exports.getConfig (/Users/jwalton/myProject/node_modules/gh/lib/configs.js:80:18)
    at Object.<anonymous> (/Users/jwalton/myProject/node_modules/gh/lib/cmds/user.js:21:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by henricavalcante** [comment]
I got problems installing by iojs.

**Comment by henvic** [comment]
Sorry. We don't support 0.10 anymore. I bet you're trying to use the newest version and it's failing because of so. We won't fix it.

@henricavalcante, please open an issue for your specific problem.

**Comment by henricavalcante** [comment]
I had problem trying to install on raspberry + iojs, but not anymore.
