### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by blaquans** [node-gh/gh#391]
I've got the following error : 

    root@debian:~# gh gi
/    usr/local/lib/node_modules/gh/lib/exec.js:21
        exec = child_process.spawnSync(cmd, args, options);
                         ^
    TypeError: Object #<Object> has no method 'spawnSync'
        at Object.exports.spawnSync (/usr/local/lib/node_modules/gh/lib/exec.js:21:26)
        at Object.exports.getNodeModulesGlobalPath (/usr/local/lib/node_modules/gh/lib/configs.js:29:23)
        at Object.exports.run (/usr/local/lib/node_modules/gh/lib/cmd.js:216:17)
        at Object.<anonymous> (/usr/local/lib/node_modules/gh/bin/gh.js:20:26)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)

I've got the following system : Debian 8.0

**Comment by henvic** [comment]
What version of node are you using? 0.12? Please take a look at https://github.com/node-gh/gh/issues/362#issuecomment-113010481

Please tell me the versions of gh and node-js:
```
gh --version
node --version
```

**Comment by henvic** [comment]
@blaquans any news about that?

**Comment by henvic** [comment]
Closing due to inactivity.

If you still have the issues please provide the request details and reopen the ticket.
