### ISSUE TITLE
error: src refspec pr-LPS-59282-67-reviewed does not match any.

### ISSUE THREAD

**Issue by arboliveira** [node-gh/gh#415]
_TL;DR_ branch name **LPS-59282-pr-67-reviewed** munged to **pr-LPS-59282-67-reviewed** somewhere

```
$ gh --version
gh 1.11.13
gh-jira 0.5.7
```

```
$ git status
On branch LPS-59282-pr-67-reviewed
nothing to commit, working directory clean
```

```
$ gh pr --submit arturbr --issue LPS-59282 --title 'LPS-59282 Unable to initialize Elasticsearch cluster after node with "0" index is shutdown'
Submitting pull request to @arturbr
error: src refspec pr-LPS-59282-67-reviewed does not match any.
error: failed to push some refs to 'git@github.com:arboliveira/liferay-portal.git'
/usr/local/lib/node_modules/gh/lib/exec.js:54
        throw err;
              ^
Error: Child process terminated with error code 1
    at Object.exports.spawnSyncStream (/usr/local/lib/node_modules/gh/lib/exec.js:50:15)
    at Object.exports.push (/usr/local/lib/node_modules/gh/lib/git.js:64:17)
    at /usr/local/lib/node_modules/gh/lib/cmds/pull-request.js:728:17
    at /usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:713:13
    at iterate (/usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (/usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:281:9)
    at _parallel (/usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:712:9)
    at Object.async.series (/usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:734:9)
    at PullRequest.submit (/usr/local/lib/node_modules/gh/lib/cmds/pull-request.js:758:11)
    at /usr/local/lib/node_modules/gh/lib/cmds/pull-request.js:988:18
```

**Comment by protoEvangelion** [comment]
Here are some common problems that lead to that error: https://stackoverflow.com/questions/4181861/src-refspec-master-does-not-match-any-when-pushing-commits-in-git

I don't think this is related to **node-gh** but if you think otherwise please let me know :smile:
