### ISSUE TITLE
Listing all issues throws an error

### ISSUE THREAD

**Issue by shinzui** [node-gh/gh#427]
Hi, I am new to gh. I just tried to configure it in order to manage issues from the command line but I am getting an error when trying to list issues. 

```
$ gh --version
$ gh 1.12.4

$ npm list -g --depth=0 | grep gh
$ ├── gh@1.12.4
```

``` bash
gh is --verbose

DEBUG: ENOENT: no such file or directory, open '/Users/shinzui/Gyehoik/lib/react-sm-ui/.gh.json'
DEBUG: ENOENT: no such file or directory, open '/Users/shinzui/Gyehoik/lib/react-sm-ui/.gh.json'
DEBUG: spawnSync: git config --get remote.origin.url
DEBUG: spawnSync: git symbolic-ref --short HEAD
Listing open issues on shinzui/semantic-ui-react
/usr/local/lib/node_modules/gh/lib/cmds/issue.js:364
                    logger.colors.magenta('@' + issue.user.login + ' (' + logger.getDuration(issues.created_at) + ')'));
                                                          ^

TypeError: Cannot read property 'login' of undefined
    at /usr/local/lib/node_modules/gh/lib/cmds/issue.js:364:59
    at Array.forEach (native)
    at /usr/local/lib/node_modules/gh/lib/cmds/issue.js:360:20
    at /usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:726:13
    at /usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:269:32
    at /usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:723:17
    at /usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:167:37
    at /usr/local/lib/node_modules/gh/node_modules/github/api/v3.0.0/issues.js:127:17
```

```
$ echo $?
$ 1
```

I verified that I am properly authenticated. 

```
$ gh user
$ You're logged in as shinzui
```

**Comment by verdverm** [comment]
ditto

**Comment by verdverm** [comment]
@shinzui did you solve this eventually?

**Comment by protoEvangelion** [comment]
Looking into this.  Related: https://github.com/node-gh/gh/issues/426
