### ISSUE TITLE
Command `gh pr` failing

### ISSUE THREAD

**Issue by jdaltonchilders** [node-gh/gh#470]
When I run the `gh pr` command inside of a repo I get the following:

```
$ gh pr
Listing open pull requests on jdaltonchilders/ng-smtas
/usr/local/lib/node_modules/gh/lib/cmds/pull-request.js:442
    pulls.forEach(function (pull) {
          ^

TypeError: pulls.forEach is not a function
    at PullRequest.getPullsTemplateJson_ (/usr/local/lib/node_modules/gh/lib/cmds/pull-request.js:442:11)
    at operations (/usr/local/lib/node_modules/gh/lib/cmds/pull-request.js:571:22)
    at /usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:718:13
    at Immediate.iterate (/usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:262:13)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

**Comment by yeungegs** [comment]
Is this still an open issue? If so can you do the following (pulled from [contributing guidelines](./https://github.com/node-gh/gh/blob/master/CONTRIBUTING.md#if-youre-reporting-a-bug) with your next update? 

> 1. Verify if your problem is already solved on the latest version
> 2. Search for open issues before opening a new one
> 3. Specify what version you're using gh --version
> 4. Print the output of npm list -g --depth=0 | grep gh
> 5. Try the command that failed with --verbose to print debugging messages
> 6. Report the exit code of the gh process: echo $? after termination

Thank you!

**Comment by protoEvangelion** [comment]
@jdaltonchilders This is no longer an issue. Please let me know if you are still running into this :smile:
