### ISSUE TITLE
gh --help throws an error

### ISSUE THREAD

**Issue by julien** [node-gh/gh#637]
Hi,

I'm using `gh@1.17.2` with `node v10.15.3` and `npm 6.4.1`

When I try to issue the following command:

```sh
gh --help
```

The following error is printed to stdout

```javascript
{ Error: Cannot find module 'nock'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/jc/.local/node/lib/node_modules/gh/lib/utils.js:9:14)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3) code: 'MODULE_NOT_FOUND' }
```

EDIT: This doesn't happen with v1.17.1 but I haven't taken the time to look at all the changes to find out what was happening

**Comment by protoEvangelion** [comment]
Hey @julien, sorry for not updating you sooner! Thanks for reporting. This has been resolved in the latest release. 1.17.3

**Comment by julien** [comment]
Great, thanks @protoEvangelion
