### ISSUE TITLE
gh is --list --milestone 1 Returns error message

### ISSUE THREAD

**Issue by josemvidal** [node-gh/gh#703]
**Version number**
```shell
> gh --version
gh 2.3.0
```
**Describe the bug**
Using the `gh is --milestone` generates a Validation error:

```shell
> gh is --list --milestone 1 
Listing open issues on SCCapstone/sandbox
Error: Error listing issues
HttpError: Validation Failed
    at Object.run (/usr/local/lib/node_modules/gh/lib/cmds/issue.js:135:19)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```
but, other commands work ok:

```shell
> gh is --list                                                
Listing open issues on SCCapstone/sandbox
#96 Test gh @josemvidal (an hour ago)


> gh is --list --detailed 
Listing open issues on SCCapstone/sandbox
#96 Test gh @josemvidal (an hour ago)
milestone:  M1 - 25
https://github.com/SCCapstone/sandbox/issues/96

> gh is --list --state closed
Listing closed issues on SCCapstone/sandbox
#95 title @josemvidal (4 days ago)

> gh is --list --labels bug                                                                                       
Listing open issues on SCCapstone/sandbox

No issues on SCCapstone/sandbox

> gh is 'Node GH rocks!' 'Body with **Markdown** support'                          

Creating a new issue on SCCapstone/sandbox
https://github.com/SCCapstone/sandbox/issues/97
[hook] gh is --browser  --user SCCapstone --repo sandbox --number 97

```

So, it seems to be a problem with the `--milestone` only.
 
**To Reproduce**

```shell
gh is --list --milestone 1 
```

**Expected behavior**

List of Issues associated with Milestone 1.

**Comment by protoEvangelion** [comment]
Thanks for reporting @josemvidal I will take a look 👍
