### ISSUE TITLE
errors while fetching PR from remote

### ISSUE THREAD

**Issue by rotty3000** [node-gh/gh#746]
**Version number**
2.8.1

**Describe the bug**
```
]$ gh pr --remote upstream 2
Fetching pull request #2 into branch pr-2
remote: Enumerating objects: 78, done.
remote: Counting objects: 100% (78/78), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 45 (delta 17), reused 45 (delta 17), pack-reused 0
Unpacking objects: 100% (45/45), done.
From github.com:foo/bar
 * [new branch]          ensure-all-tests-pass-and-finish-web-integration -> pr-2
Switched to branch 'pr-2'
[hook] gh pr 2 --comment 'Just started reviewing :)'
Adding comment on pull request #2
Error: Can't comment on pull request 2.
HttpError: Not Found
    at Object.commentHandler (/usr/lib/node_modules/gh/lib/cmds/pull-request/comment.js:16:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**To Reproduce**
See above.

1. Run Cmd 'gh pr --remote <remote> <pr>'
2. See error
See above

**Expected behavior**
PR is fetched and no error results.

**Screenshots**
N/A

**Additional context**
Ubuntu Linux 19.10

**Comment by protoEvangelion** [comment]
Hmm interesting, I'm guessing we are not passing `remote: upstream` properly to the comment handler. So the fetch works correctly right? Just not the comment hook?

**Comment by rotty3000** [comment]
Correct!
