### ISSUE TITLE
Got an error [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by MattixNow** [node-gh/gh#760]
**Version number**
2.8.5

**Describe the bug**
when i type gh command i receive this
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.resolve (path.js:139:9)
    at C:\Users\Mattaio\AppData\Roaming\npm\node_modules\gh\lib\cmds\help.js:47:67
    at async C:\Users\Mattaio\AppData\Roaming\npm\node_modules\gh\lib\cmds\help.js:47:19
    at async Promise.all (index 8)
    at async Object.run (C:\Users\Mattaio\AppData\Roaming\npm\node_modules\gh\lib\cmds\help.js:46:22)
    at async C:\Users\Mattaio\AppData\Roaming\npm\node_modules\gh\lib\cmd.js:178:13 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
**To Reproduce**

1. Run Cmd 'gh'
2. See error

**Comment by protoEvangelion** [comment]
Are you using yarn 2 by any chance? I just saw this same error when upgrading, but am fixing now.

**Comment by MattixNow** [comment]
i chose to stay with yarn 1.x.x

Le mar. 10 mars 2020 à 02:32, Ryan Garant <notifications@github.com> a
écrit :

**Comment by protoEvangelion** [comment]
Does this seem to be resolved with the latest version of gh?
```
npm i -g gh@2.8.6
```

**Comment by MattixNow** [comment]
Got an error on the 2.8.6 version 
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.resolve (path.js:139:9)
    at C:\Users\Mattaio\AppData\Roaming\npm\node_modules\gh\lib\cmds\help.js:47:67
    at async C:\Users\Mattaio\AppData\Roaming\npm\node_modules\gh\lib\cmds\help.js:47:19
    at async Promise.all (index 8)
    at async Object.run (C:\Users\Mattaio\AppData\Roaming\npm\node_modules\gh\lib\cmds\help.js:46:22)
    at async C:\Users\Mattaio\AppData\Roaming\npm\node_modules\gh\lib\cmd.js:178:13 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by protoEvangelion** [comment]
What was the exact cmd you ran?
